### ISSUE TITLE
Latest home assistant version seems to have broken everything 

### ISSUE THREAD

**Issue by ecto1a2003** [damienheiser/ha-rainforest-emu2#9]
Nothing seems to work right with the latest home assistant version. The only thing that populates is instant useage

**Comment by ecto1a2003** [comment]
found in log

Logger: root
Source: custom_components/rainforest/sensor.py:136
Integration: rainforest ([documentation](https://github.com/damienheiser/home-assistant/blob/master/custom_components/rainforest/readme.md), [issues](https://github.com/damienheiser/home-assistant/issues))
First occurred: 11:04:19 PM (1 occurrences)
Last logged: 11:04:19 PM

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/config/custom_components/rainforest/sensor.py", line 136, in serial_read
    if (reader.in_waiting > 0):
  File "/usr/local/lib/python3.9/site-packages/serial/serialposix.py", line 549, in in_waiting
    s = fcntl.ioctl(self.fd, TIOCINQ, TIOCM_zero_str)
OSError: [Errno 5] I/O error

**Comment by ecto1a2003** [comment]
![image](https://user-images.githubusercontent.com/16028846/162133155-99364d39-33e9-4e46-a595-70cb6067c783.png)

**Comment by ecto1a2003** [comment]
confirmed by trying 2022.3 home assistant again as test - works as expected

**Comment by jschulman** [comment]
confirmed as well.

**Comment by vvrockhound** [comment]
same here. current usage is valid but total is unknown which breaks the utility meter function

**Comment by vvrockhound** [comment]
HACS shows a new repository version: 1.1 trying it out now

**Comment by ecto1a2003** [comment]
Tried that one too. Easier setup. I still need to make my own helpers to tweak it. If I get adventurous I might extend this guys stuffSent via the Samsung Galaxy S10+, an AT&T 5G Evolution capable smartphone
-------- Original message --------From: vvrockhound ***@***.***> Date: 4/11/22  5:14 PM  (GMT-08:00) To: damienheiser/ha-rainforest-emu2 ***@***.***> Cc: ecto1a2003 ***@***.***>, Author ***@***.***> Subject: Re: [damienheiser/ha-rainforest-emu2] Latest home assistant version seems to have broken everything  (Issue #9) 
HACS shows a new repository version: 1.1 trying it out now

**Comment by tmulroy1** [comment]
Same issue here. All attributes are no longer available.

**Comment by ecto1a2003** [comment]
I made a integral helper based on left side to get the total back. Just feed it current usage. Then make a utility meter helper off of the integral one and you can put that back in the energy dashboard.Sent via the Samsung Galaxy S10+, an AT&T 5G Evolution capable smartphone
-------- Original message --------From: vvrockhound ***@***.***> Date: 4/11/22  5:03 PM  (GMT-08:00) To: damienheiser/ha-rainforest-emu2 ***@***.***> Cc: ecto1a2003 ***@***.***>, Author ***@***.***> Subject: Re: [damienheiser/ha-rainforest-emu2] Latest home assistant version seems to have broken everything  (Issue #9) 
same here. current usage is valid but total is unknown which breaks the utility meter function

**Comment by blueshiftlabs** [comment]
There was a breaking change to HA's integration API that meant a small change was required. My pull request #10 will fix it.
